# Generated by Django 6.0.7 on 2026-08-05 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Auction Title')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active / Bidding Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.PositiveIntegerField(verbose_name='Lot Number')),
                ('base_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price per kg (₹)')),
                ('highest_bid_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Highest Bid per kg (₹)')),
                ('is_sold', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auctions.auction')),
                ('harvest_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_lot', to='estates.harvestbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bid Amount per kg (₹)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.lot')),
            ],
        ),
    ]
