# Generated by Django 6.0 on 2026-08-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="lot",
            options={"ordering": ["lot_number"]},
        ),
    ]
