# Generated by Django 6.0.7 on 2026-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Auction Description'),
        ),
    ]
