# Generated by Django 6.0.7 on 2026-08-18 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('ACRE', 'Acre'), ('CENT', 'Cent')], max_length=10, null=True, verbose_name='Area Unit'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_address',
            field=models.TextField(blank=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company/Business Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='cardamom_plants',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Cardamom Plants'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='farm_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Farm Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='farm_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Farm Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Farm Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('BUYER', 'Buyer')], default='BUYER', max_length=10, verbose_name='Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
