# Generated by Django 6.0.7 on 2026-08-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address / Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified User'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Spices Board / Trading License Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Seller / Cardamom Farmer'), ('BUYER', 'Buyer / Trader'), ('AUCTIONEER', 'Auctioneer / Spices Board Rep'), ('ADMIN', 'System Administrator')], default='SELLER', max_length=20, verbose_name='User Role'),
        ),
    ]
