# Generated by Django 6.0.7 on 2026-08-18 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_area_unit_user_business_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cardamom_plants',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farm_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farm_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farm_name',
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company/Business Name')),
                ('business_type', models.CharField(max_length=100, verbose_name='Business Type')),
                ('business_address', models.TextField(verbose_name='Business Address')),
                ('business_details', models.TextField(blank=True, null=True, verbose_name='Business Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255, verbose_name='Farm Name')),
                ('farm_location', models.CharField(max_length=255, verbose_name='Farm Location')),
                ('farm_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Farm Area')),
                ('area_unit', models.CharField(choices=[('ACRE', 'Acre'), ('CENT', 'Cent')], max_length=10, verbose_name='Area Unit')),
                ('cardamom_plants', models.PositiveIntegerField(verbose_name='Number of Cardamom Plants')),
                ('cultivation_details', models.TextField(blank=True, null=True, verbose_name='Cultivation Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
