# Generated by Django 6.0.7 on 2026-08-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_is_verified_user_license_number_and_more'),
        ('users', '0004_create_default_admin'),
    ]

    operations = [
    ]
