# Generated by Django 6.1 on 2026-09-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_conflicting_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='business_details',
            field=models.TextField(blank=True, default='', verbose_name='Business Details'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='cultivation_details',
            field=models.TextField(blank=True, default='', verbose_name='Cultivation Details'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Seller / Cardamom Farmer'), ('BUYER', 'Buyer / Trader'), ('AUCTIONEER', 'Auctioneer / Spices Board Rep'), ('ADMIN', 'System Administrator')], max_length=10, verbose_name='Role'),
        ),
    ]
