# Generated by Django 6.0.7 on 2026-09-12 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_buyerprofile_business_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='Created by Admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, default='', verbose_name='Suspension Reason'),
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('target_model', models.CharField(max_length=50, verbose_name='Target Model')),
                ('target_id', models.CharField(max_length=50, verbose_name='Target ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason / Remarks')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
