# Generated by Django 6.0 on 2026-09-13 14:36

import carda_link.users.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auction_cancellation_reason_auction_description"),
        ("users", "0007_user_created_by_admin_user_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="gst_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="GST / Business Registration Number",
            ),
        ),
        migrations.AddField(
            model_name="buyerprofile",
            name="purchase_capacity",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Expected Purchase Capacity",
            ),
        ),
        migrations.AddField(
            model_name="buyerprofile",
            name="registration_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="buyer_certificates/",
                verbose_name="Business License / Registration Certificate",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="bank_account_holder",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Bank Account Holder Name",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="bank_account_number",
            field=carda_link.users.fields.EncryptedCharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Bank Account Number",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="bank_ifsc",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Bank IFSC Code"
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="cultivation_method",
            field=models.CharField(
                choices=[
                    ("ORGANIC", "Organic"),
                    ("CONVENTIONAL", "Conventional"),
                    ("MIXED", "Mixed"),
                ],
                default="CONVENTIONAL",
                max_length=20,
                verbose_name="Cultivation Method",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="district",
            field=models.CharField(
                choices=[
                    ("ALAPPUZHA", "Alappuzha"),
                    ("ERNAKULAM", "Ernakulam"),
                    ("IDUKKI", "Idukki"),
                    ("KANNUR", "Kannur"),
                    ("KASARAGOD", "Kasaragod"),
                    ("KOLLAM", "Kollam"),
                    ("KOTTAYAM", "Kottayam"),
                    ("KOZHIKODE", "Kozhikode"),
                    ("MALAPPURAM", "Malappuram"),
                    ("PALAKKAD", "Palakkad"),
                    ("PATHANAMTHITTA", "Pathanamthitta"),
                    ("THIRUVANANTHAPURAM", "Thiruvananthapuram"),
                    ("THRISSUR", "Thrissur"),
                    ("WAYANAD", "Wayanad"),
                ],
                default="IDUKKI",
                max_length=30,
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="ownership_proof",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="seller_documents/",
                verbose_name="Land Ownership / Cultivation Proof",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="taluk",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Taluk"
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="village",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Village"
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("EXPORTER", "Exporter"),
                    ("WHOLESALER", "Wholesaler"),
                    ("TRADER", "Trader"),
                    ("PROCESSOR", "Processor"),
                    ("RETAILER", "Retailer"),
                ],
                default="TRADER",
                max_length=50,
                verbose_name="Business Type",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="area_unit",
            field=models.CharField(
                choices=[("ACRE", "Acre"), ("CENT", "Cent")],
                default="ACRE",
                max_length=10,
                verbose_name="Area Unit",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="farm_location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Farm Location"
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Message")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Target Link",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("OUTBID", "Outbid Alert"),
                            ("AUCTION", "Auction Event"),
                            ("LOT_WON", "Lot Won"),
                            ("INVOICE", "Invoice & Settlement"),
                            ("BATCH", "Harvest Batch Quality"),
                            ("SYSTEM", "System Notification"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                        verbose_name="Notification Type",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_by",
                        to="auctions.lot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("buyer", "lot")},
            },
        ),
    ]
