# Generated by Django 6.0.7 on 2026-08-05 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Estate Name')),
                ('location', models.CharField(default='Idukki, Kerala', max_length=255, verbose_name='Location / District')),
                ('area_in_acres', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Area (Acres)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(verbose_name='Harvest Date')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight (kg)')),
                ('grade', models.CharField(choices=[('AGEB', 'Alleppey Green Extra Bold'), ('AGB', 'Alleppey Green Bold'), ('AGS', 'Alleppey Green Superior'), ('UNGRADED', 'Ungraded / Mixed')], default='UNGRADED', max_length=20, verbose_name='Cardamom Grade')),
                ('quality_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_batches', to='estates.estate')),
            ],
        ),
    ]
