# Generated by Django 6.1 on 2026-08-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='estate',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Estate Full Address'),
        ),
        migrations.AddField(
            model_name='estate',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Estate Description / Overview'),
        ),
        migrations.AddField(
            model_name='estate',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Owner / Contact Person Name'),
        ),
        migrations.AddField(
            model_name='estate',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact Phone Number'),
        ),
        migrations.AddField(
            model_name='estate',
            name='primary_photo',
            field=models.ImageField(blank=True, null=True, upload_to='estates/photos/', verbose_name='Primary Cover Photo'),
        ),
        migrations.AddField(
            model_name='estate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='area_in_acres',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Area (Acres)'),
        ),
        migrations.CreateModel(
            name='EstatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estates/gallery/', verbose_name='Estate Photo')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Photo Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='estates.estate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
