# Generated by Django 6.0.7 on 2026-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_alter_estate_options_estate_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestbatch',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Is Rejected'),
        ),
        migrations.AddField(
            model_name='harvestbatch',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='harvestbatch',
            name='grade',
            field=models.CharField(choices=[('AGEB', 'Alleppey Green Extra Bold'), ('AGB', 'Alleppey Green Bold'), ('AGS', 'Alleppey Green Superior'), ('AGS1', 'Alleppey Green Superior 1'), ('AGS2', 'Alleppey Green Superior 2'), ('UNGRADED', 'Ungraded / Mixed')], default='UNGRADED', max_length=20, verbose_name='Cardamom Grade'),
        ),
    ]
